server:
  port: 8098
  
spring:
  application:
    name: Inventory Application
  datasource:
    url: jdbc:h2:mem:pearlpay:MODE=MySQL
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2
      
logging:
  level:
    com.pearlpay.training: DEBUG